default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: library_development
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: library_test

production:
  primary: &primary_production
    <<: *default
    database: library_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: library_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: library_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: library_production_cable
    migrations_paths: db/cable_migrate